### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by zzzzzzzzzoe** [AXYZdong/axyzdong.github.io#1]
哥，能不能问一下jeckyll和nodejs分别是哪个版本呀？
![image](https://github.com/AXYZdong/axyzdong.github.io/assets/98593913/8525b3d4-f332-408e-9b09-4c8cd3b34f62)

**Comment by AXYZdong** [comment]
- jeckyll 4.2.2
- nodejs 10.19.0

**Comment by zzzzzzzzzoe** [comment]
谢谢哥
